### ISSUE TITLE
Ripple-Lib Client Libraries Needed!

### ISSUE THREAD

**Issue by dradding** [ripplelabsbounties/ripple-lib-client-libraries#1]
If you are planning on building a Ripple-Lib Client Library please submit a proposal on [Bountysource](https://www.bountysource.com/issues/2614301-ripple-lib-client-libraries-needed/proposals) and email us at [developers@ripple.com](mailto:developers@ripple.com) to let us know that you have submitted a proposal.

For more information on the Ripple Labs Bounty Program please checkout the [guidelines](https://github.com/ripplelabsbounties/Ripple-Bounty-Program-Guidelines#ripple-bounty-program-guidelines).

**Comment by ishantheperson** [comment]
I'm currently porting this to .NET framework!

**Comment by dradding** [comment]
Awesome!
